### PR TITLE
fix: place `selectedRoi` as the last rendered element close #37

### LINKED ISSUE #37: Selected ROI should be in front of the other ones
When selected, an roi should be the last element rendered so that it can be interacted with (select, resize, move) even when it overlaps with other rois.

### PR DESCRIPTION
**Pull request by josoriom**

### CODE REVIEW

**Review by stropitek — COMMENTED** [review]
I wouldn't change the order in which the ROIs were created in the state. I think it's a good thing that when for example we save them, they are in the order in which they were created.

You should do this in the component.

File: src/components/api/RoiList.tsx [hunk 1]
```diff
@@ -1,9 +1,15 @@
...
 
 import { RoiBox } from './RoiBox';
 
 export function RoiList() {
-  const rois = useRois();
+  const rois = useRois().slice();
+  const { selectedRoi } = useRoiState();
+  if (selectedRoi) {
+    const index = rois.findIndex((roi) => roi.id === selectedRoi);
+    const roi = rois.splice(index, 1)[0];
```
Comment (stropitek) [inline src/components/api/RoiList.tsx:10]: Would add an assertion here about the existence of the selected roi
Shouldn't happen to run into this but I you do you'd have an error much easier to debug.

Comment (stropitek) [reply src/components/api/RoiList.tsx:10]: Yes
In general f I don't expect something to happen, I throw. It's a good way of making sure bugs are caught early.

**Review by stropitek — APPROVED** [review]
